"""Create the complete initial schema for the community site."""
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
	op.execute("CREATE EXTENSION IF NOT EXISTS citext")
	op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
	op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
	op.execute("""
		CREATE TABLE users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email CITEXT NOT NULL UNIQUE,
			display_name VARCHAR(60) NOT NULL,
			role VARCHAR(12) NOT NULL DEFAULT 'student'
				CONSTRAINT ck_users_role CHECK (role IN ('student','teacher','moderator','admin')),
			status VARCHAR(10) NOT NULL DEFAULT 'active'
				CONSTRAINT ck_users_status CHECK (status IN ('active','banned','deleted')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			last_login_at TIMESTAMPTZ NULL,
			deleted_at TIMESTAMPTZ NULL
		)
	""")
	op.execute("""
		CREATE TABLE login_tokens (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email CITEXT NOT NULL,
			token_hash CHAR(64) NOT NULL UNIQUE,
			code_hash CHAR(64) NOT NULL,
			attempts INTEGER NOT NULL DEFAULT 0,
			expires_at TIMESTAMPTZ NOT NULL,
			used_at TIMESTAMPTZ NULL,
			ip VARCHAR(45) NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)
	""")
	op.execute("""
		CREATE TABLE user_sessions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			token_hash CHAR(64) NOT NULL UNIQUE,
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			expires_at TIMESTAMPTZ NOT NULL,
			ip VARCHAR(45) NULL,
			user_agent VARCHAR(255) NULL
		)
	""")
	op.execute("""
		CREATE TABLE school_classes (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			slug VARCHAR(40) NOT NULL UNIQUE,
			name VARCHAR(60) NOT NULL,
			description VARCHAR(500) NOT NULL DEFAULT '',
			created_by BIGINT NOT NULL REFERENCES users(id),
			status VARCHAR(10) NOT NULL DEFAULT 'pending'
				CONSTRAINT ck_school_classes_status CHECK (status IN ('pending','active','hidden')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)
	""")
	op.execute("""
		CREATE TABLE class_members (
			class_id BIGINT NOT NULL REFERENCES school_classes(id) ON DELETE CASCADE,
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			role VARCHAR(10) NOT NULL DEFAULT 'member'
				CONSTRAINT ck_class_members_role CHECK (role IN ('member','owner')),
			status VARCHAR(10) NOT NULL DEFAULT 'pending'
				CONSTRAINT ck_class_members_status CHECK (status IN ('pending','approved')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			PRIMARY KEY (class_id, user_id)
		)
	""")
	op.execute("""
		CREATE TABLE tags (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(30) NOT NULL UNIQUE CONSTRAINT ck_tags_lowercase CHECK (name = lower(name))
		)
	""")
	op.execute("""
		CREATE TABLE memes (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			author_id BIGINT NOT NULL REFERENCES users(id),
			class_id BIGINT NULL REFERENCES school_classes(id),
			caption VARCHAR(300) NOT NULL DEFAULT '',
			image_path VARCHAR(200) NOT NULL,
			thumb_path VARCHAR(200) NOT NULL,
			width INTEGER NOT NULL CONSTRAINT ck_memes_width CHECK (width > 0),
			height INTEGER NOT NULL CONSTRAINT ck_memes_height CHECK (height > 0),
			likes_count INTEGER NOT NULL DEFAULT 0 CONSTRAINT ck_memes_likes_count CHECK (likes_count >= 0),
			status VARCHAR(10) NOT NULL DEFAULT 'visible'
				CONSTRAINT ck_memes_status CHECK (status IN ('visible','hidden','deleted')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)
	""")
	op.execute("""
		CREATE TABLE meme_tags (
			meme_id BIGINT NOT NULL REFERENCES memes(id) ON DELETE CASCADE,
			tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
			PRIMARY KEY (meme_id, tag_id)
		)
	""")
	op.execute("""
		CREATE TABLE meme_likes (
			meme_id BIGINT NOT NULL REFERENCES memes(id) ON DELETE CASCADE,
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			PRIMARY KEY (meme_id, user_id)
		)
	""")
	op.execute("""
		CREATE TABLE quotes (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			author_id BIGINT NOT NULL REFERENCES users(id),
			class_id BIGINT NULL REFERENCES school_classes(id),
			text VARCHAR(400) NOT NULL,
			said_by VARCHAR(80) NOT NULL,
			context VARCHAR(200) NOT NULL DEFAULT '',
			said_on DATE NULL,
			votes_count INTEGER NOT NULL DEFAULT 0 CHECK (votes_count >= 0),
			status VARCHAR(10) NOT NULL DEFAULT 'pending'
				CONSTRAINT ck_quotes_status CHECK (status IN ('pending','visible','hidden','deleted')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)
	""")
	op.execute("""
		CREATE TABLE quote_votes (
			quote_id BIGINT NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			PRIMARY KEY (quote_id, user_id)
		)
	""")
	op.execute("""
		CREATE TABLE resources (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			author_id BIGINT NOT NULL REFERENCES users(id),
			class_id BIGINT NULL REFERENCES school_classes(id),
			title VARCHAR(120) NOT NULL,
			description VARCHAR(1000) NOT NULL DEFAULT '',
			subject VARCHAR(40) NOT NULL,
			school_year SMALLINT NULL
				CONSTRAINT ck_resources_school_year CHECK (school_year IS NULL OR school_year BETWEEN 1 AND 4),
			kind VARCHAR(10) NOT NULL
				CONSTRAINT ck_resources_kind CHECK (kind IN ('notes','test','exercises','link','other')),
			url VARCHAR(500) NULL,
			file_path VARCHAR(200) NULL,
			file_name VARCHAR(200) NULL,
			file_size INTEGER NULL,
			file_mime VARCHAR(100) NULL,
			upvotes_count INTEGER NOT NULL DEFAULT 0
				CONSTRAINT ck_resources_upvotes_count CHECK (upvotes_count >= 0),
			downloads_count INTEGER NOT NULL DEFAULT 0
				CONSTRAINT ck_resources_downloads_count CHECK (downloads_count >= 0),
			status VARCHAR(10) NOT NULL DEFAULT 'visible'
				CONSTRAINT ck_resources_status CHECK (status IN ('visible','hidden','deleted')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			search_vector TSVECTOR GENERATED ALWAYS AS
				(to_tsvector('simple', title || ' ' || description || ' ' || subject)) STORED,
			CONSTRAINT ck_resources_url_xor_file
				CHECK ((url IS NOT NULL AND file_path IS NULL) OR (url IS NULL AND file_path IS NOT NULL))
		)
	""")
	op.execute("""
		CREATE TABLE resource_votes (
			resource_id BIGINT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			PRIMARY KEY (resource_id, user_id)
		)
	""")
	op.execute("""
		CREATE TABLE resource_tags (
			resource_id BIGINT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
			tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
			PRIMARY KEY (resource_id, tag_id)
		)
	""")
	op.execute("""
		CREATE TABLE reports (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			reporter_id BIGINT NOT NULL REFERENCES users(id),
			target_type VARCHAR(10) NOT NULL
				CONSTRAINT ck_reports_target_type CHECK (target_type IN ('meme','quote','resource','user','class')),
			target_id BIGINT NOT NULL,
			reason VARCHAR(20) NOT NULL
				CONSTRAINT ck_reports_reason CHECK (reason IN ('spam','harassment','personal_info','inappropriate','copyright','other')),
			details VARCHAR(500) NOT NULL DEFAULT '',
			status VARCHAR(10) NOT NULL DEFAULT 'open'
				CONSTRAINT ck_reports_status CHECK (status IN ('open','actioned','dismissed')),
			handled_by BIGINT NULL REFERENCES users(id),
			handled_at TIMESTAMPTZ NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			CONSTRAINT uq_reports_reporter_target UNIQUE (reporter_id, target_type, target_id)
		)
	""")
	op.execute("""
		CREATE TABLE takedown_requests (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(100) NOT NULL,
			contact VARCHAR(200) NOT NULL,
			target_url VARCHAR(500) NOT NULL,
			message VARCHAR(2000) NOT NULL,
			status VARCHAR(10) NOT NULL DEFAULT 'open'
				CONSTRAINT ck_takedown_requests_status CHECK (status IN ('open','done')),
			handled_by BIGINT NULL REFERENCES users(id),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)
	""")
	op.execute("""
		CREATE TABLE audit_log (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			actor_id BIGINT NULL REFERENCES users(id),
			action VARCHAR(50) NOT NULL,
			target_type VARCHAR(10) NULL,
			target_id BIGINT NULL,
			meta JSONB NOT NULL DEFAULT '{}'::jsonb,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)
	""")
	op.execute("CREATE INDEX ix_user_sessions_user_id ON user_sessions (user_id)")
	op.execute("CREATE INDEX ix_memes_status_id ON memes (status, id DESC)")
	op.execute("CREATE INDEX ix_memes_class_id ON memes (class_id)")
	op.execute("CREATE INDEX ix_quotes_status_id ON quotes (status, id DESC)")
	op.execute("CREATE INDEX ix_resources_status_id ON resources (status, id DESC)")
	op.execute("CREATE INDEX ix_resources_search_vector ON resources USING GIN (search_vector)")
	op.execute("CREATE INDEX ix_reports_status_target ON reports (status, target_type, target_id)")


def downgrade() -> None:
	for table in (
		"audit_log", "takedown_requests", "reports", "resource_tags", "resource_votes",
		"resources", "quote_votes", "quotes", "meme_likes", "meme_tags", "memes",
		"tags", "class_members", "school_classes", "user_sessions", "login_tokens", "users",
	):
		op.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
	op.execute("DROP EXTENSION IF EXISTS unaccent")
	op.execute("DROP EXTENSION IF EXISTS pg_trgm")
	op.execute("DROP EXTENSION IF EXISTS citext")
